import type { Finding } from "../types/findings.js";
import type { ScanReport, OwaspComplianceEntry } from "../types/findings.js";

export function generateMarkdownReport(report: ScanReport): string {
  const lines: string[] = [];

  lines.push("# MCP Security Scan Report");
  lines.push("");
  lines.push(`**Target:** ${report.target}`);
  lines.push(`**Scanner:** ${report.scanner} v${report.version}`);
  lines.push(`**Date:** ${report.timestamp}`);
  lines.push(`**Duration:** ${report.duration_ms}ms`);
  lines.push("");

  // Executive Summary
  lines.push("## Executive Summary");
  lines.push("");
  lines.push(`| Severity | Count |`);
  lines.push(`|----------|-------|`);
  lines.push(`| Critical | ${report.summary.critical} |`);
  lines.push(`| High | ${report.summary.high} |`);
  lines.push(`| Medium | ${report.summary.medium} |`);
  lines.push(`| Low | ${report.summary.low} |`);
  lines.push(`| Info | ${report.summary.info} |`);
  lines.push(`| **Total** | **${report.summary.total}** |`);
  lines.push("");

  // OWASP Compliance
  lines.push("## OWASP MCP Top 10 Compliance");
  lines.push("");
  lines.push("| ID | Category | Status | Findings | Highest Severity |");
  lines.push("|-----|----------|--------|----------|------------------|");
  for (const entry of report.owasp_compliance) {
    const status = entry.status === "pass" ? "PASS" : entry.status === "fail" ? "FAIL" : "N/T";
    lines.push(`| ${entry.id} | ${entry.title} | ${status} | ${entry.finding_count} | ${entry.highest_severity ?? "-"} |`);
  }
  lines.push("");

  // Score
  const passed = report.owasp_compliance.filter(e => e.status === "pass").length;
  const tested = report.owasp_compliance.filter(e => e.status !== "not_tested").length;
  const score = tested > 0 ? Math.round((passed / tested) * 100) : 0;
  lines.push(`**Compliance Score:** ${score}/100 (${passed}/${tested} categories passed)`);
  lines.push("");

  // Detailed Findings
  if (report.findings.length > 0) {
    lines.push("## Detailed Findings");
    lines.push("");

    const byCategory: Record<string, Finding[]> = {};
    for (const f of report.findings) {
      const key = `${f.owasp_mcp} — ${f.owasp_mcp_title}`;
      if (!byCategory[key]) byCategory[key] = [];
      byCategory[key].push(f);
    }

    for (const [category, findings] of Object.entries(byCategory)) {
      lines.push(`### ${category}`);
      lines.push("");

      for (const f of findings) {
        lines.push(`#### ${f.severity.toUpperCase()}: ${f.id} — ${f.title}`);
        lines.push("");
        if (f.file) {
          lines.push(`- **Location:** \`${f.file}${f.line ? `:${f.line}` : ""}${f.column ? `:${f.column}` : ""}\``);
        }
        if (f.cwe) lines.push(`- **CWE:** ${f.cwe}`);
        lines.push(`- **Evidence:** ${f.evidence}`);
        lines.push(`- **Remediation:** ${f.remediation}`);
        lines.push("");
      }
    }
  }

  // Remediation Checklist
  lines.push("## Remediation Checklist");
  lines.push("");
  const criticals = report.findings.filter(f => f.severity === "critical");
  const highs = report.findings.filter(f => f.severity === "high");

  if (criticals.length > 0) {
    lines.push("### Critical (Fix Immediately)");
    for (const f of criticals) {
      lines.push(`- [ ] ${f.id}: ${f.title}`);
    }
    lines.push("");
  }

  if (highs.length > 0) {
    lines.push("### High (Fix Soon)");
    for (const f of highs) {
      lines.push(`- [ ] ${f.id}: ${f.title}`);
    }
    lines.push("");
  }

  lines.push("---");
  lines.push(`*Generated by mcp-security-scanner v${report.version}*`);

  return lines.join("\n");
}
